from django.urls import path
from .views import (
    HealthCheckView,
    LabListView,
    LabCategoriesView,
    LabDetailView,
    UserProgressView,
    ProgressStatsView,
    LaunchInstanceView,
    SubmitAnswerView,
    CommunitySolutionListView,
    ReflectionView,
    UserRegisterView,
    MyTokenObtainPairView,
    AccessInstanceView,
    TerminateInstanceView,
    ExtendInstanceView,
    InstanceStatusView,
    CurrentInstanceView,
)


urlpatterns = [
    path(
        "health/",
        HealthCheckView.as_view(),
        name="health-check",
    ),
    path(
        "progress/",
        UserProgressView.as_view(),
        name="user-progress",
    ),
    path(
        "progress/stats/",
        ProgressStatsView.as_view(),
        name="progress-stats",
    ),
    path(
        "labs/",
        LabListView.as_view(),
        name="lab-list",
    ),
    path(
        "labs/categories/",
        LabCategoriesView.as_view(),
        name="lab-categories",
    ),
    path(
        "labs/<uuid:id>/",
        LabDetailView.as_view(),
        name="lab-detail",
    ),
    path(
        "labs/<uuid:id>/launch/",
        LaunchInstanceView.as_view(),
        name="launch-instance",
    ),
    path(
        "instances/<uuid:id>/access/",
        AccessInstanceView.as_view(),
        name="access-instance",
    ),
    path(
        "instances/<uuid:id>/status/",
        InstanceStatusView.as_view(),
        name="instance-status",
    ),
    path(
        "labs/<uuid:id>/submit/",
        SubmitAnswerView.as_view(),
        name="answer-submit",
    ),
    path(
        "labs/<uuid:id>/reflection/",
        ReflectionView.as_view(),
        name="submit-reflection",
    ),
    path(
        "labs/<uuid:id>/solutions/",
        CommunitySolutionListView.as_view(),
        name="community-solutions",
    ),
    path(
        "instances/terminate/",
        TerminateInstanceView.as_view(),
        name="terminate-instance",
    ),
    path(
        "instances/extend/",
        ExtendInstanceView.as_view(),
        name="extend-instance",
    ),
    path(
        "instances/current/",
        CurrentInstanceView.as_view(),
        name="current-instance",
    ),
]
