# Generated by Django 5.2.7 on 2026-06-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='compose_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lab',
            name='web_port',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='lab',
            name='web_service',
            field=models.CharField(default='web', max_length=100),
        ),
    ]
