# Generated by Django 5.2.7 on 2026-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lab_compose_template_lab_web_port_lab_web_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinstance',
            name='extensions_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activeinstance',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('error', 'Error')], default='creating', max_length=20),
        ),
        migrations.AlterField(
            model_name='activeinstance',
            name='container_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activeinstance',
            name='instance_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
