# Generated by Django 5.2.7 on 2026-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activeinstance_extensions_used_activeinstance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinstance',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
