# Generated by Django 5.2.7 on 2026-06-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activeinstance_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinstance',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('error', 'Error')], db_index=True, default='creating', max_length=20),
        ),
    ]
