# Generated by Django 5.2.7 on 2026-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_activeinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='db_image',
            field=models.CharField(default='mysql:8.0', max_length=255),
        ),
        migrations.AddField(
            model_name='lab',
            name='needs_db',
            field=models.BooleanField(default=True),
        ),
    ]
