# Generated by Django 5.2.7 on 2026-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lab_db_image_lab_needs_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='compose_template',
            field=models.TextField(blank=True, default='', help_text='留空 → 依 needs_db/db_image 自動產生 web(+mysql)。多服務（php+nginx、postgres…）在此貼完整 docker-compose YAML。對外服務設為 web_service；其餘自動內部互通。設定/程式碼需烤進鏡像（平台不掛主機檔），平台只對外開 web_service:web_port 並強制套用資源/安全限制。'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='db_image',
            field=models.CharField(default='mysql:8.0', help_text='compose_template 留空且 needs_db 時使用的 DB 鏡像（如 mysql:5.6）。', max_length=255),
        ),
        migrations.AlterField(
            model_name='lab',
            name='docker_image',
            field=models.CharField(help_text='單一容器靶機的 web 鏡像。多服務題改用下方 compose_template。', max_length=255),
        ),
        migrations.AlterField(
            model_name='lab',
            name='needs_db',
            field=models.BooleanField(default=True, help_text='compose_template 留空時是否附加一個 mysql 容器。不需 DB 的題取消勾選。'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='web_port',
            field=models.PositiveIntegerField(default=80, help_text='對外服務在容器內監聽的埠。'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='web_service',
            field=models.CharField(default='web', help_text='compose 中要對使用者開埠的服務名稱。', max_length=100),
        ),
    ]
