# Generated by Django 5.2.7 on 2026-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lab_compose_template_alter_lab_db_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='requires_answer',
            field=models.BooleanField(default=True, help_text='是否需要提交答案。取消勾選＝純跑靶機沙盒：無答案、無防禦表單、不計完成、不進社群解法。'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='固定答案題要交回的 flag 字串；純跑靶機題（requires_answer 取消勾選）留空即可。'),
        ),
    ]
