# Generated by Django 5.2.7 on 2026-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lab_requires_answer_alter_lab_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='expiry_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='此題靶機存活分鐘數；留空＝用全域 INSTANCE_EXPIRY_MINUTES。', null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='max_extensions',
            field=models.PositiveIntegerField(blank=True, help_text='此題最多可延長次數；留空＝用全域 INSTANCE_MAX_EXTENSIONS。', null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='web_env',
            field=models.TextField(blank=True, default='', help_text='此題 web 服務的額外環境變數，一行一個 KEY=VALUE（# 開頭為註解）。會覆蓋/補上預設模板的 DB_* 設定，讓 BYO 鏡像用不同 env 名稱時不必手寫整段 compose_template。'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='db_image',
            field=models.CharField(default='mysql:8.0', help_text='compose_template 留空且 needs_db 時使用的 DB 鏡像（如 mysql:5.6）。請用 mysql 8.0 或 5.x：8.4+ 已移除 native_password 啟動旗標，會起不來。', max_length=255),
        ),
    ]
